const GET_REQUESTED_FILM = 'GET_REQUESTED_FILM';
const GET_REQUESTED_FILM_SUCCESS = 'GET_REQUESTED_FILM_SUCCESS';
const GET_REQUESTED_FILM_FAILURE = 'GET_REQUESTED_FILM_FAILURE';

export {
  GET_REQUESTED_FILM,
  GET_REQUESTED_FILM_SUCCESS,
  GET_REQUESTED_FILM_FAILURE,
};
