const ADD_TO_FAVORITE_LIST = 'ADD_TO_FAVORITE_LIST';
const ADD_TO_FAVORITE_LIST_SUCCESS = 'ADD_TO_FAVORITE_LIST_SUCCESS';
const ADD_TO_FAVORITE_LIST_FAILURE = 'ADD_TO_FAVORITE_LIST_FAILURE';

export {
  ADD_TO_FAVORITE_LIST,
  ADD_TO_FAVORITE_LIST_SUCCESS,
  ADD_TO_FAVORITE_LIST_FAILURE,
};
